services:

  database:
    image: mariadb:11.1.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: bloc3
      MARIADB_DATABASE: bloc3
      MARIADB_USER: bloc3
      MARIADB_PASSWORD: bloc3
    ports:
      - 3306:3306

  database_seeder:
    image: mariadb:11.1.2
    volumes:
      - ./sql/schema.sql:/sql/schema.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    entrypoint: [ "bash", "-c", "sleep 10 && mariadb --user=bloc3 --password=bloc3 --host=database --port=3306 bloc3 < /sql/schema.sql && exit"] 
    depends_on:
      - database

  phpmyadmin:
      image: phpmyadmin:5.2.1
      restart: unless-stopped
      ports:
          - 8080:80
      environment:
          # we specify that we connect to an arbitrary server with the flag below
          # "arbitrary" means you're able to specify which database server to use on login page of phpmyadmin      
          - PMA_ARBITRARY=1
      depends_on:
        - database_seeder