version: '3'
services:

  bloc3:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor/
    ports:
      - 8080:80   # Expose port 8080

  phpmyadmin:
      image: phpmyadmin:5.2.1
      restart: unless-stopped
      ports:
          - 8081:80
      environment:
          - PMA_ARBITRARY=1
      depends_on:
        - database

  # Note: For Cloud Run, you would typically use a managed database service like Google Cloud SQL
  database:
    image: mariadb:11.1.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: bloc3
      MARIADB_DATABASE: bloc3
      MARIADB_USER: bloc3
      MARIADB_PASSWORD: bloc3
    ports:
      - 3306:3306
