name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Spécifiez la version de Python

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Spécifiez la version de PHP
        tools: composer, phpunit # Outils PHP à installer

    - name: Install PHP dependencies
      run: composer install

    # Ajoutez ici d'autres étapes de test pour Python et PHP
    - name: Run Python tests
      run: |
        # Commande pour exécuter les tests Python
        python -m unittest

    - name: Run PHP tests
      run: |
        # Commande pour exécuter les tests PHP
        phpunit tests/
