name: PHP Unit Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: bloc3
          MYSQL_DATABASE: bloc3
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-php-app .

    - name: Run PHPUnit tests inside Docker container
      run: docker run my-php-app ./vendor/bin/phpunit

